name: CI/CD

on:
  push:
    branches:
      - feature/*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js 16
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "16"
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Run ESLint
  #       run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  merge_to_dev:
    name: Merge to Dev
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to dev
        uses: pullreminders/merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          method: squash
          commit-message: "Merge pull request #${{ github.event.pull_request.number }} from feature branch"
          branch: "dev"
